spring:
  application:
    name: oauth2-jwt
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_CLIENT_ID
            client-secret: YOUR_CLIENT_SECRET
            scope:
              - email
              - profile
app:
  security:
    jwt:
      issuer: oauth2-jwt
      public:
        key: classpath:app.public.key
      private:
        key: classpath:app.private.key
    web:
      cors:
        allowed-origin: http://localhost:3000