spring:
  application:
    name: oauth2

  api:
    jwt:
      issuer: oauth2-project
      public:
        key: classpath:app.pub
      private:
        key: classpath:app.key

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_CLIENT_ID
            client-secret: YOUR_CLIENT_SECRET
            scope:
              - email
              - profile