spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_CLIENT_ID
            client-secret: YOUR_CLIENT_SECRET
            scope:
              - email
              - profile

application:
  jwt:
    issuer: oauth2
    public:
      key: classpath:app.pub
    private:
      key: classpath:app.key
  web:
    cors:
      allowed-origin: http://localhost:3000
